import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';

interface ActionPlan {
    id: number;
    symbol: string;
    stock_name: string;
    action: string;
    time_range: string;
    description: string;
    reasoning: string;
    created_at: string;
    original_response: string;
    status: 'pending' | 'completed';
    model?: string;
}

interface ActionTimelineProps {
    symbol: string | undefined;
}

export const ActionTimeline: React.FC<ActionTimelineProps> = ({ symbol }) => {
    const [actions, setActions] = useState<ActionPlan[]>([]);
    const [loading, setLoading] = useState(false);
    const [selectedAction, setSelectedAction] = useState<ActionPlan | null>(null);

    const API_BASE_URL = (import.meta as any).env?.VITE_ASHARE_API_URL || 'http://localhost:8000';

    useEffect(() => {
        if (!symbol) {
            setActions([]);
            return;
        }

        setLoading(true);
        fetch(`${API_BASE_URL}/api/actions/${symbol}`)
            .then(res => res.json())
            .then(data => {
                setActions(data);
                setLoading(false);
            })
            .catch(err => {
                console.error("Failed to fetch actions", err);
                setLoading(false);
            });
    }, [symbol]);

    const handleStatusToggle = async (action: ActionPlan) => {
        const newStatus = action.status === 'completed' ? 'pending' : 'completed';

        // Optimistic update
        setActions(prev => prev.map(a => a.id === action.id ? { ...a, status: newStatus } : a));

        try {
            await fetch(`${API_BASE_URL}/api/actions/${action.id}/status?status=${newStatus}`, {
                method: 'PATCH'
            });
        } catch (e) {
            console.error("Failed to update status", e);
            // Revert on failure
            setActions(prev => prev.map(a => a.id === action.id ? { ...a, status: action.status } : a));
        }
    };

    if (!symbol) return <div className="timeline-empty">Select a stock to view action plans.</div>;
    if (loading) return <div className="timeline-loading">Loading actions...</div>;
    if (actions.length === 0) return <div className="timeline-empty">No action plans found for {symbol}.</div>;

    return (
        <div className="action-timeline">
            <h2>Action Plans for {symbol}</h2>
            <div className="timeline-list">
                {actions.map(action => (
                    <div key={action.id} className={`timeline-card action-${action.action.toLowerCase()} ${action.status === 'completed' ? 'completed' : ''}`}>
                        <div className="card-header">
                            <span className={`badge ${action.action.toLowerCase()}`}>{action.action.toUpperCase()}</span>
                            <span className="time-range">{action.time_range}</span>
                            <div className="meta-info">
                                <span className="created-at">{new Date(action.created_at).toLocaleString()}</span>
                                {action.model && <span className="model-tag" title="Generated by AI Model">🤖 {action.model}</span>}
                            </div>
                            <label className="status-checkbox">
                                <input
                                    type="checkbox"
                                    checked={action.status === 'completed'}
                                    onChange={() => handleStatusToggle(action)}
                                />
                                Done
                            </label>
                        </div>
                        <div className="card-body">
                            <p className="description">{action.description}</p>
                            <p className="reasoning"><strong>Basis:</strong> {action.reasoning}</p>
                        </div>
                        <button className="view-original-btn" onClick={() => setSelectedAction(action)}>
                            View Original Analysis
                        </button>
                    </div>
                ))}
            </div>

            {selectedAction && (
                <div className="modal-overlay" onClick={() => setSelectedAction(null)}>
                    <div className="modal-content" onClick={e => e.stopPropagation()}>
                        <h3>Original Analysis</h3>
                        <div className="modal-scroll markdown-body">
                            <ReactMarkdown>{selectedAction.original_response}</ReactMarkdown>
                        </div>
                        <button className="close-btn" onClick={() => setSelectedAction(null)}>Close</button>
                    </div>
                </div>
            )}
        </div>
    );
};
