RULE_INDICATOR_CATALOG = [
    # 大盘与市场整体指标
    {
        "indicator_id": "market_all_index_change_pct",
        "name": "全A指数单日跌幅",
        "category": "大盘",
        "description": "衡量市场整体风险",
        "formula": "(当日收盘价 - 前日收盘价) / 前日收盘价 × 100%",
        "data_source": "全A指数(000985.SH/881001.WI)日线",
        "params": {"index_symbol": "000985.SH"},
        "default_enabled": False,
        "sort_order": 10,
    },
    {
        "indicator_id": "market_up_count",
        "name": "市场上涨家数",
        "category": "大盘",
        "description": "衡量市场情绪",
        "formula": "当日上涨个股数量（涨跌幅>0）",
        "data_source": "交易所公开数据/市场广度",
        "params": {},
        "default_enabled": False,
        "sort_order": 11,
    },
    {
        "indicator_id": "market_down_count",
        "name": "市场下跌家数",
        "category": "大盘",
        "description": "衡量市场情绪",
        "formula": "当日下跌个股数量（涨跌幅<0）",
        "data_source": "交易所公开数据/市场广度",
        "params": {},
        "default_enabled": False,
        "sort_order": 12,
    },
    {
        "indicator_id": "market_liquidity_crisis_trigger",
        "name": "流动性危机触发",
        "category": "大盘",
        "description": "上涨家数低于阈值触发",
        "formula": "market_up_count < threshold",
        "data_source": "基于市场上涨家数",
        "params": {"threshold": 300, "score_contribution": -1.0},
        "default_enabled": False,
        "sort_order": 13,
    },
    # 个股基础指标
    {
        "indicator_id": "stock_current_price",
        "name": "当前价格",
        "category": "个股基础",
        "description": "最新成交价",
        "formula": "最新收盘价或实时价",
        "data_source": "日线/实时行情",
        "params": {},
        "default_enabled": True,
        "sort_order": 20,
    },
    {
        "indicator_id": "stock_return_6m",
        "name": "N日累计涨幅",
        "category": "个股基础",
        "description": "近N个月的总涨幅",
        "formula": "(当前价 - N个月前收盘价) / N个月前收盘价 × 100%",
        "data_source": "历史日线",
        "params": {"months": 6, "up_min": 20.0, "down_max": -20.0, "score_contribution": 0.3},
        "default_enabled": True,
        "sort_order": 21,
    },
    {
        "indicator_id": "stock_turnover_rate",
        "name": "单日换手率",
        "category": "个股基础",
        "description": "当日成交量 / 流通股本 × 100%",
        "formula": "volume / float_shares × 100%",
        "data_source": "行情+股本数据",
        "params": {},
        "default_enabled": False,
        "sort_order": 22,
    },
    {
        "indicator_id": "stock_turnover_ratio_3m",
        "name": "换手率异常倍数",
        "category": "个股基础",
        "description": "当日换手率 / 近M个月平均换手率",
        "formula": "turnover_rate_today / avg_turnover_rate(M个月)",
        "data_source": "行情+股本数据",
        "params": {"months": 3},
        "default_enabled": False,
        "sort_order": 23,
    },
    {
        "indicator_id": "stock_pe_ttm",
        "name": "市盈率(TTM)",
        "category": "个股基础",
        "description": "当前总市值 / 过去12个月净利润",
        "formula": "market_cap / net_profit_ttm",
        "data_source": "基本面",
        "params": {},
        "default_enabled": False,
        "sort_order": 24,
    },
    {
        "indicator_id": "stock_pe_percentile",
        "name": "市盈率历史分位",
        "category": "个股基础",
        "description": "当前PE在历史中的位置",
        "formula": "PE历史分位数",
        "data_source": "历史PE",
        "params": {"years": 5},
        "default_enabled": False,
        "sort_order": 25,
    },
    {
        "indicator_id": "stock_pb_lf",
        "name": "市净率(LF)",
        "category": "个股基础",
        "description": "最新报告期市净率",
        "formula": "market_cap / net_assets",
        "data_source": "基本面",
        "params": {},
        "default_enabled": False,
        "sort_order": 26,
    },
    # 趋势与动量指标
    {
        "indicator_id": "bias_ma20",
        "name": "乖离率(BIAS)20日",
        "category": "趋势动量",
        "description": "股价与MA20偏离度",
        "formula": "(当前价 - MA20) / MA20 × 100%",
        "data_source": "日线",
        "params": {"ma": 20, "up_min": 1.5, "down_max": -4.0, "score_contribution": 0.5},
        "default_enabled": True,
        "sort_order": 30,
    },
    {
        "indicator_id": "bias_ma60",
        "name": "乖离率(BIAS)60日",
        "category": "趋势动量",
        "description": "股价与MA60偏离度",
        "formula": "(当前价 - MA60) / MA60 × 100%",
        "data_source": "日线",
        "params": {"ma": 60, "up_min": 1.0, "down_max": -6.0, "score_contribution": 0.4},
        "default_enabled": True,
        "sort_order": 31,
    },
    {
        "indicator_id": "ma5",
        "name": "MA5",
        "category": "趋势动量",
        "description": "5日移动平均线",
        "formula": "过去5日收盘价均值",
        "data_source": "日线",
        "params": {"window": 5},
        "default_enabled": True,
        "sort_order": 32,
    },
    {
        "indicator_id": "ma10",
        "name": "MA10",
        "category": "趋势动量",
        "description": "10日移动平均线",
        "formula": "过去10日收盘价均值",
        "data_source": "日线",
        "params": {"window": 10},
        "default_enabled": True,
        "sort_order": 33,
    },
    {
        "indicator_id": "ma20",
        "name": "MA20",
        "category": "趋势动量",
        "description": "20日移动平均线",
        "formula": "过去20日收盘价均值",
        "data_source": "日线",
        "params": {"window": 20},
        "default_enabled": True,
        "sort_order": 34,
    },
    {
        "indicator_id": "ma60",
        "name": "MA60",
        "category": "趋势动量",
        "description": "60日移动平均线",
        "formula": "过去60日收盘价均值",
        "data_source": "日线",
        "params": {"window": 60},
        "default_enabled": True,
        "sort_order": 35,
    },
    {
        "indicator_id": "macd",
        "name": "MACD",
        "category": "趋势动量",
        "description": "指数平滑异同平均线",
        "formula": "DIF=EMA12-EMA26; DEA=DIF的9日EMA; 柱=(DIF-DEA)*2",
        "data_source": "日线",
        "params": {"fast": 12, "slow": 26, "signal": 9, "hist_pos": 0.0, "hist_neg": 0.0, "score_contribution": 0.6},
        "default_enabled": True,
        "sort_order": 36,
    },
    {
        "indicator_id": "macd_red_days",
        "name": "MACD红柱连续天数",
        "category": "趋势动量",
        "description": "MACD柱>0的连续天数",
        "formula": "统计最近连续满足MACD柱>0的天数",
        "data_source": "日线",
        "params": {"min_red_days": 3, "zero_fail_max": 0, "score_contribution": 0.3},
        "default_enabled": True,
        "sort_order": 37,
    },
    {
        "indicator_id": "trendline_support",
        "name": "趋势线支撑位",
        "category": "趋势动量",
        "description": "上升趋势线在当前的位置",
        "formula": "连接两个以上低点的直线，计算今日对应值",
        "data_source": "日线",
        "params": {},
        "default_enabled": False,
        "sort_order": 38,
    },
    {
        "indicator_id": "key_resistance",
        "name": "关键阻力位",
        "category": "趋势动量",
        "description": "前期高点或密集成交区",
        "formula": "最近明显高点或MA60",
        "data_source": "日线",
        "params": {"window": 60},
        "default_enabled": True,
        "sort_order": 39,
    },
    # 成交量与量能指标
    {
        "indicator_id": "volume_daily",
        "name": "当日成交量",
        "category": "量能",
        "description": "当日成交股数（或金额）",
        "formula": "日线成交量",
        "data_source": "日线",
        "params": {},
        "default_enabled": True,
        "sort_order": 40,
    },
    {
        "indicator_id": "volume_ma5",
        "name": "5日均量",
        "category": "量能",
        "description": "过去5日成交量均值",
        "formula": "(V1+V2+V3+V4+V5)/5",
        "data_source": "日线",
        "params": {"window": 5},
        "default_enabled": True,
        "sort_order": 41,
    },
    {
        "indicator_id": "volume_ratio_5",
        "name": "量能倍数",
        "category": "量能",
        "description": "当日成交量 / 5日均量",
        "formula": "volume_today / volume_ma5",
        "data_source": "日线",
        "params": {"up_min": 1.2, "down_max": 0.7, "score_contribution": 0.5},
        "default_enabled": True,
        "sort_order": 42,
    },
    {
        "indicator_id": "turnover_relative_ratio",
        "name": "换手率相对倍数",
        "category": "量能",
        "description": "当日换手率 / 近3个月平均换手率",
        "formula": "turnover_rate_today / avg_turnover_rate(3个月)",
        "data_source": "行情+股本数据",
        "params": {"months": 3},
        "default_enabled": False,
        "sort_order": 43,
    },
    {
        "indicator_id": "next_day_volume_ratio",
        "name": "次日量能比例",
        "category": "量能",
        "description": "次日成交量 / 突破日成交量",
        "formula": "volume_next / volume_breakout",
        "data_source": "日线",
        "params": {},
        "default_enabled": False,
        "sort_order": 44,
    },
    # 板块与相对强度指标
    {
        "indicator_id": "sector_index_change_pct",
        "name": "板块指数当日涨幅",
        "category": "板块相对",
        "description": "所属板块指数的涨跌幅",
        "formula": "(板块指数收盘价 - 前日)/前日 × 100%",
        "data_source": "板块指数",
        "params": {},
        "default_enabled": False,
        "sort_order": 50,
    },
    {
        "indicator_id": "sector_strong_count",
        "name": "板块内强势股数量",
        "category": "板块相对",
        "description": "板块内涨幅超过阈值的个股数量",
        "formula": "count(change_pct > X%)",
        "data_source": "板块成分股",
        "params": {"threshold_pct": 5},
        "default_enabled": False,
        "sort_order": 51,
    },
    {
        "indicator_id": "relative_strength_sector",
        "name": "相对强度(个股/板块)",
        "category": "板块相对",
        "description": "个股涨幅 / 板块涨幅",
        "formula": "stock_change_pct / sector_change_pct",
        "data_source": "个股+板块",
        "params": {},
        "default_enabled": False,
        "sort_order": 52,
    },
    {
        "indicator_id": "sector_rank",
        "name": "板块涨幅排名",
        "category": "板块相对",
        "description": "板块在全市场的排名",
        "formula": "按板块涨幅排序",
        "data_source": "全市场板块",
        "params": {},
        "default_enabled": False,
        "sort_order": 53,
    },
    # 左侧潜伏专用指标
    {
        "indicator_id": "low_volume_sideways",
        "name": "缩量横盘",
        "category": "左侧潜伏",
        "description": "成交量萎缩+价格波动小",
        "formula": "MA5量 < MA20量×0.8 且 ATR% 低于阈值",
        "data_source": "日线",
        "params": {"vol_ratio_max": 0.8, "atr_pct_max": 2.0, "score_contribution": 0.6},
        "default_enabled": True,
        "sort_order": 60,
    },
    {
        "indicator_id": "low_volatility",
        "name": "波动率极低",
        "category": "左侧潜伏",
        "description": "波动率处于历史低位",
        "formula": "ATR14 <= ATR60均值×0.7",
        "data_source": "日线",
        "params": {"atr_ratio_max": 0.7, "window": 60, "score_contribution": 0.5},
        "default_enabled": True,
        "sort_order": 61,
    },
    {
        "indicator_id": "catalyst_window",
        "name": "催化剂有效期",
        "category": "左侧潜伏",
        "description": "未来1-3个月有预期事件",
        "formula": "人工输入/财经日历",
        "data_source": "手工/财经日历",
        "params": {},
        "default_enabled": False,
        "sort_order": 62,
    },
    # 右侧突破专用指标
    {
        "indicator_id": "daily_change_pct",
        "name": "单日涨幅",
        "category": "右侧突破",
        "description": "当日涨跌幅",
        "formula": "(收盘价 - 前收盘)/前收盘 × 100%",
        "data_source": "日线",
        "params": {"up_min": 2.0, "down_max": -2.0, "score_contribution": 0.4},
        "default_enabled": True,
        "sort_order": 70,
    },
    {
        "indicator_id": "close_above_key_resistance",
        "name": "收盘价站稳关键位",
        "category": "右侧突破",
        "description": "收盘价高于关键阻力位",
        "formula": "close > key_resistance",
        "data_source": "日线",
        "params": {"score_contribution": 0.7},
        "default_enabled": True,
        "sort_order": 71,
    },
    {
        "indicator_id": "two_day_hold_above",
        "name": "连续两日站稳",
        "category": "右侧突破",
        "description": "连续两日收盘价高于阻力位",
        "formula": "close[-1] > R && close[-2] > R",
        "data_source": "日线",
        "params": {"score_contribution": 0.9},
        "default_enabled": True,
        "sort_order": 72,
    },
    {
        "indicator_id": "mild_breakout_days",
        "name": "温和突破有效天数",
        "category": "右侧突破",
        "description": "N日内有M日收盘价高于阻力位",
        "formula": "count(close > R, window=N) >= M",
        "data_source": "日线",
        "params": {"window": 3, "min_days": 2, "score_contribution": 0.6},
        "default_enabled": True,
        "sort_order": 73,
    },
    # 风险与观察期指标
    {
        "indicator_id": "breakdown_short_support",
        "name": "跌破短期支撑",
        "category": "风险观察",
        "description": "收盘价低于MA5或MA10",
        "formula": "close < MA5 or close < MA10",
        "data_source": "日线",
        "params": {"score_contribution": -0.7},
        "default_enabled": True,
        "sort_order": 80,
    },
    {
        "indicator_id": "volume_breakdown_ma20",
        "name": "放量跌破MA20",
        "category": "风险观察",
        "description": "成交量放大且收盘价低于MA20",
        "formula": "volume > MA5量×1.2 且 close < MA20",
        "data_source": "日线",
        "params": {"volume_ratio": 1.2, "score_contribution": -0.8},
        "default_enabled": True,
        "sort_order": 81,
    },
    {
        "indicator_id": "price_near_cost",
        "name": "未脱离成本区",
        "category": "风险观察",
        "description": "当前价在买入价附近",
        "formula": "|price-avg_cost|/avg_cost <= X%",
        "data_source": "持仓成本",
        "params": {"threshold_pct": 2, "score_contribution": -0.6},
        "default_enabled": False,
        "sort_order": 82,
    },
    # 止盈与移动止损指标
    {
        "indicator_id": "first_target",
        "name": "第一目标位",
        "category": "止盈止损",
        "description": "最近强阻力位",
        "formula": "前高/通道上轨/整数关口",
        "data_source": "日线",
        "params": {},
        "default_enabled": True,
        "sort_order": 90,
    },
    {
        "indicator_id": "trailing_stop",
        "name": "移动止损位",
        "category": "止盈止损",
        "description": "随股价上移的止损",
        "formula": "最高价回撤一定比例或跌破MA10",
        "data_source": "日线",
        "params": {"trail_pct": 0.05},
        "default_enabled": True,
        "sort_order": 91,
    },
    # 时间周期相关
    {
        "indicator_id": "days_to_earnings",
        "name": "距离财报披露天数",
        "category": "时间周期",
        "description": "距离下次财报公告日的天数",
        "formula": "earnings_date - today",
        "data_source": "财经日历",
        "params": {},
        "default_enabled": False,
        "sort_order": 100,
    },
    {
        "indicator_id": "days_to_holiday",
        "name": "长假前交易日",
        "category": "时间周期",
        "description": "距离长假开始的天数",
        "formula": "holiday_start - today",
        "data_source": "节假日历",
        "params": {},
        "default_enabled": False,
        "sort_order": 101,
    },
]
